%% Example driver script for simulating "model_1" model.
% This file was automatically generated by OneModel.
% Any changes you make to it will be overwritten the next time
% the file is generated.

% clear all;
% close all;

%% First simulation (Find the steady-state when substrate is not limiting).

% Init model.
m0 = model_initialize();

p0 = m0.p;

p0.cell__p_A__omega = 50;
p0.cell__p_A__k_b   = 5.1754;
p0.cell__p_A__k_u   = 117.2305;

% Solver options.
opt0 = odeset('AbsTol',1e-8,'RelTol',1e-8);
opt0 = odeset(opt0,'Mass',m0.M);

% Simulation time span.
tspan = [0 1e9];

[~,x] = ode15s(@(t,x) m0.ode(t,x,p0),tspan,m0.x0,opt0);

%% Second simulation (Real simulation with the bioreactor).

% Init model.
m = model_batch();

p = m.p;

p.cell__p_A__omega = 50;
p.cell__p_A__k_b   = 5.1754;
p.cell__p_A__k_u   = 117.2305;

% Solver options.
opt = odeset('AbsTol',1e-8,'RelTol',1e-8);
opt = odeset(opt,'Mass',m.M);

% Simulation time span.
tspan = [0 480*1.5];

% Set the initial condition using the previous simulation.
x0 = m.x0;
x0(1) = x(end,1);
x0(2) = x(end,2);
x0(3) = x(end,3);
x0(4) = x(end,4);
x0(5) = x(end,5);

[t,x] = ode15s(@(t,x) m.ode(t,x,p),tspan,x0,opt);
t = t/60;
out = m.simout2struct(t,x,p);

%% Colors.

myColors.blue   = [0, 0.4470, 0.7410];
myColors.orange = [0.8500, 0.3250, 0.0980];
myColors.yellow = [0.9290, 0.6940, 0.1250];
myColors.purple = [0.4940, 0.1840, 0.5560];
myColors.green  = [0.4660, 0.6740, 0.1880];
myColors.cyan   = [0.3010, 0.7450, 0.9330];
myColors.red    = [0.6350, 0.0780, 0.1840];

myColors.array = {
    myColors.blue
    myColors.orange
    myColors.yellow
    myColors.purple
    myColors.green
    myColors.cyan
    myColors.red
    };

%% Plot result.
close all;

lineWidth = 1.2;

fig = figure('units','centimeters','position',[0 0 6 14.5]);

subplot(3,1,1);

yyaxis left;
set(gca,'ycolor',myColors.array{1});
ax = gca;
ax.FontSize = 6; 

yyaxis right;
set(gca,'ycolor',myColors.array{2});
ax = gca;
ax.FontSize = 6; 

yyaxis left;
plot(out.t, out.bio__s,'Color',myColors.array{1},'LineWidth',lineWidth);
ylabel('Substrate [g L$^{-1}$]','interpreter','latex','FontSize',9);
ylim([0 4]);
xlim([0 12]);
xticks([0 3 6 9 12]);

yyaxis right;
plot(out.t, out.bio__x,'Color',myColors.array{2},'LineWidth',lineWidth);
ylabel('Biomass [g L$^{-1}$]','interpreter','latex','FontSize',9);
ylim([0 2]);
xlim([0 12]);
xticks([0 3 6 9 12]);

% title('Bioreactor model','FontSize',9); 
xlabel('Time [h]','interpreter','latex','FontSize',9); 

subplot(3,1,2);

yyaxis left;
set(gca,'ycolor',myColors.array{7});
ax = gca;
ax.FontSize = 6; 

yyaxis right;
set(gca,'ycolor',myColors.array{4});
ax = gca;
ax.FontSize = 6; 

yyaxis left;
plot(out.t, out.cell__mu+0.00005,'Color',myColors.array{7},'LineWidth',lineWidth);
ylabel('Growth rate [min$^{-1}$]','interpreter','latex','FontSize',9);
ylim([0 0.02]);
xlim([0 12]);
xticks([0 3 6 9 12]);

yyaxis right;
plot(out.t, out.cell__J_host_sum,'Color',myColors.array{4},'LineWidth',lineWidth);
ylabel('$N_r J_r + N_{nr} J_{nr}$ [adim]','interpreter','latex','FontSize',9);
ylim([0 3000]);
xlim([0 12]);
xticks([0 3 6 9 12]);

% title('Host model','FontSize',9);
xlabel('Time [h]','interpreter','latex','FontSize',9); 

subplot(3,1,3);

yyaxis left;
set(gca,'ycolor',myColors.array{5});
ax = gca;
ax.FontSize = 6; 

yyaxis right;
set(gca,'ycolor',myColors.array{6});
ax = gca;
ax.FontSize = 6; 

yyaxis left;
plot(out.t, out.cell__p_A__m,'Color',myColors.array{5},'LineWidth',lineWidth);
ylabel('Protein A [fg cell$^{-1}$]','interpreter','latex','FontSize',9);
ylim([0 30]);
xlim([0 12]);
xticks([0 3 6 9 12]);

yyaxis right;
plot(out.t, out.cell__p_A__J,'Color',myColors.array{6},'LineWidth',lineWidth);
ylabel('$J_A$ [adim]','interpreter','latex','FontSize',9);
ylim([0 120]);

% title('Synthetic gene model','FontSize',9);
xlabel('Time [h]','interpreter','latex','FontSize',9); 

print(fig,'./figs/figure_1b.eps','-depsc');